import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        heading:  ['var(--font-manrope)', 'sans-serif'],
        body:     ['var(--font-inter)',   'sans-serif'],
        headline: ['var(--font-manrope)', 'sans-serif'],
        label:    ['var(--font-inter)',   'sans-serif'],
      },
      colors: {
        // ── Stitch / Azure Clarity Design System ──────────────────────
        'surface-dim':               '#d9dadb',
        'surface-container-highest': '#e1e3e4',
        'on-tertiary-container':     '#ffc2a7',
        'primary-fixed':             '#d7e2ff',
        'tertiary':                  '#722b00',
        'on-primary-container':      '#bbd0ff',
        'on-error-container':        '#93000a',
        'on-tertiary':               '#ffffff',
        'primary-fixed-dim':         '#acc7ff',
        'primary-container':         '#0056b3',
        'inverse-primary':           '#acc7ff',
        'inverse-on-surface':        '#f0f1f2',
        'tertiary-fixed-dim':        '#ffb694',
        'on-secondary':              '#ffffff',
        'inverse-surface':           '#2e3132',
        'surface-container-high':    '#e7e8e9',
        'surface-variant':           '#e1e3e4',
        'on-tertiary-fixed':         '#351000',
        'surface':                   '#f8f9fa',
        'secondary':                 '#4c5e84',
        'on-secondary-container':    '#475a7f',
        'on-surface-variant':        '#424752',
        'tertiary-fixed':            '#ffdbcc',
        'secondary-fixed-dim':       '#b3c7f1',
        'on-secondary-fixed-variant':'#34476a',
        'on-error':                  '#ffffff',
        'on-primary-fixed':          '#001a40',
        'secondary-container':       '#bfd2fd',
        'error':                     '#ba1a1a',
        'tertiary-container':        '#983c00',
        'surface-bright':            '#f8f9fa',
        'on-tertiary-fixed-variant': '#7b2f00',
        'surface-container':         '#edeeef',
        'surface-tint':              '#115cb9',
        'primary':                   '#003f87',
        'on-primary-fixed-variant':  '#004491',
        'surface-container-low':     '#f3f4f5',
        'on-surface':                '#191c1d',
        'outline-variant':           '#c2c6d4',
        'on-background':             '#191c1d',
        'outline':                   '#727784',
        'error-container':           '#ffdad6',
        'on-secondary-fixed':        '#041b3c',
        'secondary-fixed':           '#d7e2ff',
        'surface-container-lowest':  '#ffffff',
        'on-primary':                '#ffffff',
        'background':                '#f8f9fa',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
